class Spree::PaymentMethodTransactionsReport::PaymentMethodRevenueDistributionChart
  def initialize(result)
    @time_dimension = result.time_dimension
    @grouped_by_payment_method = result.observations.group_by(&:payment_method_name)
    @time_series = []
    if @grouped_by_payment_method.values.first.present?
      @time_series = @grouped_by_payment_method.values.first.collect { |observation| observation.send(@time_dimension) }
    end
  end

  def to_h
    {
      id: 'payment-methods',
      json: {
        chart: { type: 'column' },
        title: {
          useHTML: true,
          text: "<span class='chart-title'>Payment Methods</span><span class='fa fa-question-circle' data-toggle='tooltip' title=' Compare the revenue generated by different Payment methods such as CC, Check etc.'></span>"
        },
        xAxis: { categories: @time_series },
        yAxis: {
          title: { text: 'value($)' }
        },
        tooltip: { valuePrefix: '$' },
        legend: {
          layout: 'vertical',
          align: 'right',
          verticalAlign: 'middle',
          borderWidth: 0
        },
        series: @grouped_by_payment_method.collect { |key, value| { name: key, data: value.map(&:payment_amount) }
        }
      }
    }
  end
end
